title: 2018 Gene Golub SIAM Summer School
description: June 17-30, 2018, Breckenridge, Colorado, USA
author: the organizers of g2s3 2018
google_analytics: UA-107320781-1
author_email: info@g2s3.com
theme: jekyll-theme-cayman
